// --------------------------------------------------------------------------------
// The MIT License (MIT)
//
// Copyright (c) 2014-2016 Shiny Development
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// --------------------------------------------------------------------------------

#import <UIKit/UIKit.h>
#import "SDStatusBarOverriderPost10_0.h"

typedef NS_ENUM(int, StatusBarItem10_0) {
  DoNotDisturb = 1,
  // 2
  SignalStrengthBars = 3,
  // 4
  // 5
  // 6
  // 7
  // 8
  BatteryDetail = 9,
  // 10
  // 11
  Bluetooth = 12,
  // 13
  Alarms = 14,
  // 15
  // 16
  // 17
  RotationLock = 18,
  // 19
  // 20
  // 21
  // 22
  // 23
  // 24
  // 25
  // 26
  // 27
  // 28
  // 29
  // 30
  // 31
  // 32
  // 33
};

typedef NS_ENUM(unsigned int, BatteryState) {
  BatteryStateUnplugged = 0
};

typedef struct {
  bool enabled[34];
  char timeString[64];
  int signalStrengthRaw;
  int signalStrength;
  char carrierString[100];
  char x6[100];
  char x7[2][100];
  char x8[1024];
  unsigned int x9;
  int x10;
  int x11;
  unsigned int x12;
  int battery;
  BatteryState batteryState;
  char batteryString[150];
  int x16;
  int x17;
  unsigned int x18 : 1;
  unsigned int x19 : 1;
  unsigned int x20 : 1;
  char backButtonBundleId[256];
  unsigned int bluetoothConnected;
  unsigned int x23 : 1;
  unsigned int x24 : 1;
  unsigned int x25 : 1;
  unsigned int x26 : 1;
  unsigned int x27;
  unsigned int x28 : 1;
  unsigned int x29 : 1;
  unsigned int x30 : 1;
  char x31[256];
  char x32[256];
  char x33[100];
  char x34[100];
  unsigned int x35 : 1;
  unsigned int x36 : 1;
} StatusBarRawData;

typedef struct {
  bool shouldOverrideEnabled[34];
  unsigned int shouldOverrideTimeString : 1;
  unsigned int shouldOverrideSignalStrengthRaw : 1;
  unsigned int shouldOverrideSignalStrength : 1;
  unsigned int shouldOverrideCarrierString : 1;
  unsigned int x6 : 2;
  unsigned int x7 : 1;
  unsigned int x8 : 1;
  unsigned int x9 : 1;
  unsigned int x10 : 1;
  unsigned int x11 : 1;
  unsigned int x12 : 1;
  unsigned int shouldOverrideBattery : 1;
  unsigned int shouldOverrideBatteryState : 1;
  unsigned int shouldOverrideBatteryString : 1;
  unsigned int x16 : 1;
  unsigned int x17 : 1;
  unsigned int x18 : 1;
  unsigned int x19 : 1;
  unsigned int shouldOverrideBluetoothConnected : 1;
  unsigned int x21 : 1;
  unsigned int x22;
  unsigned int x23 : 1;
  unsigned int x24 : 1;
  unsigned int x25 : 1;
  unsigned int x26 : 1;
  StatusBarRawData values;
} StatusBarOverrideData;

@class UIStatusBarServer;

// http://localhost:10000/protocols/UIStatusBarServerClient.h (commented some methods, and added structs)
/* Generated by RuntimeBrowser.
 */

@protocol UIStatusBarServerClient

@required

- (void)statusBarServer:(UIStatusBarServer *)arg1 didReceiveStatusBarData:(const StatusBarRawData *)data withActions:(int)arg3;
- (void)statusBarServer:(UIStatusBarServer *)arg1 didReceiveStyleOverrides:(int)arg2;
- (void)statusBarServer:(UIStatusBarServer *)arg1 didReceiveGlowAnimationState:(bool)arg2 forStyle:(long long)arg3;
- (void)statusBarServer:(UIStatusBarServer *)arg1 didReceiveDoubleHeightStatusString:(NSString *)arg2 forStyle:(long long)arg3;

@end

// http://localhost:10000/classes/UIStatusBarServer.h (commented some methods, and added structs)
/* Generated by RuntimeBrowser.
 */

@interface UIStatusBarServer : NSObject

@property (nonatomic, strong) id<UIStatusBarServerClient> statusBar;

+ (void)postStatusBarOverrideData:(StatusBarOverrideData *)arg1;
+ (void)permanentizeStatusBarOverrideData;
+ (const StatusBarRawData *)getStatusBarData;
+ (StatusBarOverrideData *)getStatusBarOverrideData;

@end

@implementation SDStatusBarOverriderPost10_0

@synthesize timeString;
@synthesize carrierName;
@synthesize bluetoothConnected;
@synthesize bluetoothEnabled;

- (void)enableOverrides
{
  StatusBarOverrideData *overrides = [UIStatusBarServer getStatusBarOverrideData];

  // Set 9:41 time in current localization
  strcpy(overrides->values.timeString, [self.timeString cStringUsingEncoding:NSUTF8StringEncoding]);
  overrides->shouldOverrideTimeString = 1;

  // Enable 5 bars of mobile (iPhone only)
  if ([UIDevice currentDevice].userInterfaceIdiom == UIUserInterfaceIdiomPhone) {
    overrides->shouldOverrideEnabled[SignalStrengthBars] = 1;
    overrides->values.enabled[SignalStrengthBars] = 1;
    overrides->shouldOverrideSignalStrength = 1;
    overrides->values.signalStrength = 5;
  }

  // Remove carrier text for iPhone, set it to "iPad" for the iPad
  overrides->shouldOverrideCarrierString = 1;
  NSString *carrierText = self.carrierName;
  if ([carrierText length] <= 0) {
    carrierText = ([UIDevice currentDevice].userInterfaceIdiom == UIUserInterfaceIdiomPhone) ? @"" : @"iPad";
  }
  strcpy(overrides->values.carrierString, [carrierText cStringUsingEncoding:NSUTF8StringEncoding]);

  // Battery: 100% and unpluged
  overrides->shouldOverrideBattery = 1;
  overrides->values.battery = 100;
  overrides->shouldOverrideBatteryState = 1;
  overrides->values.batteryState = BatteryStateUnplugged;

  // Bluetooth
  overrides->shouldOverrideEnabled[Bluetooth] = !!self.bluetoothEnabled;
  overrides->values.enabled[Bluetooth] = !!self.bluetoothEnabled;
  if (self.bluetoothEnabled) {
    overrides->shouldOverrideBluetoothConnected = self.bluetoothConnected;
    overrides->values.bluetoothConnected = self.bluetoothConnected;
  }

  // Actually update the status bar
  [UIStatusBarServer postStatusBarOverrideData:overrides];

  // Lock in the changes, reset simulator will remove this
  [UIStatusBarServer permanentizeStatusBarOverrideData];
}

- (void)disableOverrides
{
  StatusBarOverrideData *overrides = [UIStatusBarServer getStatusBarOverrideData];

  // Remove all overrides that use the array of bools
  bzero(overrides->shouldOverrideEnabled, sizeof(overrides->shouldOverrideEnabled));
  bzero(overrides->values.enabled, sizeof(overrides->values.enabled));

  // Remove specific overrides (separate flags)
  overrides->shouldOverrideTimeString = 0;
  overrides->shouldOverrideSignalStrength = 0;
  overrides->shouldOverrideBattery = 0;
  overrides->shouldOverrideBatteryState = 0;
  overrides->shouldOverrideBluetoothConnected = 0;

  // Carrier text (it's an override to set it back to the default)
  overrides->shouldOverrideCarrierString = 1;
  strcpy(overrides->values.carrierString, [NSLocalizedString(@"Carrier", @"Carrier") cStringUsingEncoding:NSUTF8StringEncoding]);

  // Actually update the status bar
  [UIStatusBarServer postStatusBarOverrideData:overrides];

  // Have to call this to remove all the overrides
  [UIStatusBarServer permanentizeStatusBarOverrideData];
}

@end
